CSC = /cygdrive/c/windows/Microsoft.NET/Framework/v4.0.30319/csc.exe
objects = TestGame.cs Network.cs Neuron.cs Termination.cs Weight.cs Example.cs \
	Bot.cs ConnectFourBoard.cs
TestGame.exe: $(objects)
	$(CSC) $(objects)
